export const projectDetails = [
    {
    name: "CucumisLush",
    imageUrl: "/lush.svg",
    SourceCode: "https://github.com/brisibe",
    url: "http://174.138.0.201:3300/",
    details: "A online store for fabricated goods and service booking",
    tags: ["React", "Redux", "Cloudinary", "Nodejs", "Bootstrap"],
    isPublic: true,
  },
 
  {
    name: "Task Tracker",
    imageUrl: "/tasktracker.svg",
    SourceCode: "https://github.com/brisibe/task-tracker",
    url: "https://tasktrackerr.vercel.app",
    details: "A task tracker that help you stay productive",
    tags: ["React"],
    isPublic: true,
  },
  {
    name: "Cryptoo",
    imageUrl: "/crypto.svg",
    SourceCode: "https://github.com/brisibe/live-crypto",
    url: "https://cryptoo.vercel.app",
    details: "A live cryptocurrency price Tracker.",
    tags: ["React", "Styled-Components", "Charts.js"],
    isPublic: true,
  },
  {
    name: "Shopbeta",
    imageUrl: "/shopbeta.svg",
    SourceCode: "https://github.com/brisibe/shopbeta-server",
    url: "https://shopbeta.vercel.app",
    details: "The most affordable online shopping mall...",
    tags: [".NetCore", "Azure", "Reactjs", "Redux", "Mssql"],
    isPublic: true,
  },
   {
     name: "Get A Job",
    imageUrl: "/getajob.svg",
    SourceCode: "https://github.com/brisibe/conclase-assessment",
    url: "https://getajob-eight.vercel.app",
    details: "A responsive landing page translated from a design",
    tags: ["React", "Styled-component"],
    isPublic: true,
  },
  {
    name: "Brisibe.dev",
    imageUrl: "/brisibe.svg",
    SourceCode: "https://github.com/brisibe/my-portfolio",
    url: "https://brisibe.dev",
    details: "My Portfolio website",
    tags: ["Next.js"],
    isPublic: true,
  },
];
