export const projectDetails = [
  {
    name: "Brisibe.dev",
    imageUrl: "#",
    SourceCode: "https://github.com/brisibe/my-portfolio",
    url: "#",
    details: "My portfolio website...",
    tags: ["Next.js", "css"],
    isPublic: true,
  },
  {
    name: "Brisibe.dev",
    imageUrl: "#",
    SourceCode: "https://github.com/brisibe/my-portfolio",
    url: "#",
    details: "My portfolio website...",
    tags: ["Next.js", "css"],
    isPublic: true,
  },
  {
    name: "Brisibe.dev",
    imageUrl: "#",
    SourceCode: "https://github.com/brisibe/my-portfolio",
    url: "#",
    details: "My portfolio website...",
    tags: ["Next.js", "css"],
    isPublic: true,
  },
  {
    name: "Brisibe.dev",
    imageUrl: "#",
    SourceCode: "https://github.com/brisibe/my-portfolio",
    url: "#",
    details: "My portfolio website...",
    tags: ["Next.js", "css"],
    isPublic: true,
  },
  {
    name: "Brisibe.dev",
    imageUrl: "#",
    SourceCode: "https://github.com/brisibe/my-portfolio",
    url: "#",
    details: "My portfolio website...",
    tags: ["Next.js", "css"],
    isPublic: true,
  },
  {
    name: "Brisibe.dev",
    imageUrl: "#",
    SourceCode: "https://github.com/brisibe/my-portfolio",
    url: "#",
    details: "My portfolio website...",
    tags: ["Next.js", "css"],
    isPublic: true,
  },
  {
    name: "Brisibe.dev",
    imageUrl: "#",
    SourceCode: "https://github.com/brisibe/my-portfolio",
    url: "#",
    details: "My portfolio website...",
    tags: ["Next.js", "css"],
    isPublic: true,
  },
  // {
  //   name: "ShopBetaa",
  //   imageUrl: "#",
  //   SourceCode: "#",
  //   url: "#",
  //   details: "just a random message to stand as place holder text",
  //   tags: ["React", "javascript"],
  // },
  // {
  //   name: "ShopBetaa",
  //   imageUrl: "#",
  //   SourceCode: "#",
  //   url: "#",
  //   details: "just a random message to stand as place holder text",
  //   tags: ["React", "javascript"],
  // },
  // {
  //   name: "ShopBetaa",
  //   imageUrl: "#",
  //   SourceCode: "#",
  //   url: "#",
  //   details: "just a random message to stand as place holder text",
  //   tags: ["React", "javascript"],
  // },
];
